#!/usr/bin/env node
/* Generate read-only calendar data from lunar-javascript 1.7.7 (MIT). */
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const source = process.argv[2];
const expected = '9750324bfe1aa63c146f8c72b1143df924466c11c8a5277d7d9225c541a18aaa';
if (!source || crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex') !== expected) {
    throw new Error('Supply the unmodified https://cdn.jsdelivr.net/npm/lunar-javascript@1.7.7/lunar.js');
}
const {Solar} = require(path.resolve(source));
const root = path.resolve(__dirname, '..');
const deities = ['青龙','明堂','天刑','朱雀','金匮','天德','白虎','玉堂','天牢','玄武','司命','勾陈'];
const terms = ['', '冬至','小寒','大寒','立春','雨水','惊蛰','春分','清明','谷雨','立夏','小满','芒种',
    '夏至','小暑','大暑','立秋','处暑','白露','秋分','寒露','霜降','立冬','小雪','大雪'];
const phrases = new Map();
function phrase(items) {
    const text = items.join(' ');
    if (!phrases.has(text)) phrases.set(text, phrases.size);
    return phrases.get(text);
}
const rows = [];
for (let date = new Date('2000-01-01T12:00:00Z'); date.getUTCFullYear() < 2100; date.setUTCDate(date.getUTCDate() + 1)) {
    const year = date.getUTCFullYear();
    const lunar = Solar.fromYmd(year, date.getUTCMonth() + 1, date.getUTCDate()).getLunar();
    const month = lunar.getMonth();
    const bits = Math.abs(month) + (month < 0 ? 12 : 0) + (lunar.getDay() << 5) + ((year - lunar.getYear()) << 10);
    const deity = deities.indexOf(lunar.getDayTianShen());
    const term = terms.indexOf(lunar.getJieQi());
    if (deity < 0 || term < 0 || year - lunar.getYear() > 1) throw new Error('Unexpected upstream value');
    rows.push(`    {${bits},${deity},${term},${phrase(lunar.getDayYi())},${phrase(lunar.getDayJi())}},`);
}
if (phrases.size > 65535 || rows.length !== 36525) throw new Error('Calendar bounds exceeded');
const quote = text => JSON.stringify(text);
const output = [
    '/* Generated by tools/generate_passport_calendar.js; lunar-javascript 1.7.7, MIT.',
    ' * Source SHA-256: ' + expected,
    ' * China civil dates 2000-01-01..2099-12-31, evaluated at 00:00 (same as the approved demo).',
    ' * See passport_calendar_license.txt. Do not edit generated records. */',
    'static const char *const s_calendar_phrases[] = {',
    ...[...phrases.keys()].map(text => `    ${quote(text)},`), '};',
    'static const passport_day_record_t s_calendar_records[] = {', ...rows, '};', ''
];
fs.writeFileSync(path.join(root, 'main/passport_calendar_data.inc'), output.join('\n'));
console.log(`${rows.length} dates, ${phrases.size} deduplicated phrases`);
