#!/usr/bin/env python3
"""Generate the licensed CJK subset and the application's original pixel digits."""

import argparse
import hashlib
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "assets" / "fonts"
DIGITS = [
    ["01110", "11011", "11011", "11011", "11011", "11011", "01110"],
    ["00100", "01100", "00100", "00100", "00100", "00100", "01110"],
    ["11110", "00011", "00011", "01110", "11000", "11000", "11111"],
    ["11110", "00011", "00011", "01110", "00011", "00011", "11110"],
    ["11011", "11011", "11011", "11111", "00011", "00011", "00011"],
    ["11111", "11000", "11000", "11110", "00011", "00011", "11110"],
    ["01111", "11000", "11000", "11110", "11011", "11011", "01110"],
    ["11111", "00011", "00110", "00110", "01100", "01100", "01100"],
    ["01110", "11011", "11011", "01110", "11011", "11011", "01110"],
    ["01110", "11011", "11011", "01111", "00011", "00011", "11110"],
]


def symbols() -> str:
    text = (ROOT / "main" / "workout_ui.c").read_text(encoding="utf-8")
    chinese = {char for char in text if ord(char) > 126 and char.isprintable()}
    return "".join(chr(value) for value in range(32, 127)) + "".join(sorted(chinese))


def pixel_font() -> None:
    glyphs = [["0", "0", "0", "0", "0", "1", "1"], *DIGITS]
    bitmap = []
    descriptions = ["    {0},"]
    for rows in glyphs:
        bits = "".join("".join(bit * 5 for bit in row) * 5 for row in rows)
        index = len(bitmap)
        bitmap.extend(int((bits + "0" * 7)[i:i + 8], 2) for i in range(0, len(bits), 8))
        width = len(rows[0]) * 5
        advance = 12 if width == 5 else 30
        descriptions.append(f"    {{.bitmap_index = {index}, .adv_w = {advance * 16}, .box_w = {width}, .box_h = 35, .ofs_x = 0, .ofs_y = 0}},")
    lines = ["/* Original application pixel digits; generated by tools/generate_workout_fonts.py. */",
             '#include "lvgl.h"', "static const uint8_t glyph_bitmap[] = {"]
    lines += ["    " + ", ".join(f"0x{b:02x}" for b in bitmap[i:i + 16]) + "," for i in range(0, len(bitmap), 16)]
    lines += ["};", "static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {", *descriptions, "};",
              "static const lv_font_fmt_txt_cmap_t cmaps[] = {",
              "    {.range_start = 46, .range_length = 1, .glyph_id_start = 1, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},",
              "    {.range_start = 48, .range_length = 10, .glyph_id_start = 2, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY},", "};",
              "static const lv_font_fmt_txt_dsc_t font_dsc = {",
              "    .glyph_bitmap = glyph_bitmap, .glyph_dsc = glyph_dsc, .cmaps = cmaps,",
              "    .bpp = 1, .cmap_num = 2, .kern_scale = 16, .bitmap_format = 0,", "};",
              "const lv_font_t workout_digits_35 = {",
              "    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt, .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,",
              "    .line_height = 35, .base_line = 0, .dsc = &font_dsc,", "};", ""]
    (OUTPUT / "workout_digits_35.c").write_text("\n".join(lines), encoding="utf-8")


def network_font(font: Path, converter: Path) -> None:
    """Keep broad CJK support for dynamic SSIDs in Flash, separate from the UI subsets."""
    destination = OUTPUT / "workout_network_font_16.c"
    subprocess.run(["node", str(converter), "--font", str(font),
                    "--range", "0x20-0x7e,0x3000-0x303f,0x3400-0x9fff,0xff00-0xffef",
                    "--size", "16", "--bpp", "2", "--format", "lvgl", "--no-compress", "--no-kerning",
                    "--lv-include", "lvgl.h", "--lv-font-name", "workout_network_font_16",
                    "--output", str(destination)], check=True)
    source = destination.read_text(encoding="utf-8")
    source = re.sub(r" \* Opts:.*\n", " * Generated with lv_font_conv 1.5.3; see tools/generate_workout_fonts.py.\n", source)
    source = "/* Noto Sans CJK SC; SIL OFL 1.1, see NotoSansCJKsc-OFL.txt. */\n" + source
    destination.write_text(source.rstrip() + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", required=True, type=Path)
    parser.add_argument("--converter", required=True, type=Path, help="lv_font_conv 1.5.3 JavaScript entry point")
    parser.add_argument("--network-font", action="store_true", help="Also regenerate the broad 16px CJK SSID font")
    args = parser.parse_args()
    version = subprocess.check_output(["node", str(args.converter), "--version"], text=True).strip()
    if version != "1.5.3":
        raise SystemExit("Use the documented lv_font_conv 1.5.3.")
    inventory = symbols()
    OUTPUT.mkdir(exist_ok=True)
    (OUTPUT / "workout_symbols.txt").write_text(inventory + "\n", encoding="utf-8")
    for size in (12, 16, 20):
        subprocess.run(["node", str(args.converter), "--font", str(args.font), "--symbols", inventory,
                        "--size", str(size), "--bpp", "2", "--format", "lvgl", "--no-compress", "--no-kerning",
                        "--lv-include", "lvgl.h", "--lv-font-name", f"workout_font_{size}",
                        "--output", str(OUTPUT / f"workout_font_{size}.c")], check=True)
        destination = OUTPUT / f"workout_font_{size}.c"
        source = destination.read_text(encoding="utf-8")
        source = re.sub(r" \* Opts:.*\n", " * Generated with lv_font_conv 1.5.3; see tools/generate_workout_fonts.py.\n", source)
        source = "/* Noto Sans CJK SC subset; SIL OFL 1.1, see NotoSansCJKsc-OFL.txt. */\n" + source
        destination.write_text(source.rstrip() + "\n", encoding="utf-8")
    array = ",".join(f"0x{ord(char):04X}" for char in inventory)
    header = "#pragma once\n#include <stdint.h>\nstatic const uint32_t workout_font_codepoints[] = {" + array + "};\n"
    (OUTPUT / "workout_font_inventory.h").write_text(header, encoding="utf-8")
    pixel_font()
    if args.network_font:
        network_font(args.font, args.converter)
    print("Font SHA-256:", hashlib.sha256(args.font.read_bytes()).hexdigest())
    print("Codepoints:", len(inventory), "Sizes: 12, 16, 20; BPP: 2")


if __name__ == "__main__":
    main()
